name = "nextpint-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "nextpint-db"
database_id = "YOUR_DATABASE_ID" # Replace with actual ID after creation

[env.production]
name = "nextpint-api"
# Workers routes will be set up in Cloudflare dashboard

[[env.production.d1_databases]]
binding = "DB"
database_name = "nextpint-db"
database_id = "YOUR_DATABASE_ID" # Replace with actual ID after creation

[env.development]
name = "nextpint-api-dev"

[[env.development.d1_databases]]
binding = "DB"
database_name = "nextpint-db"
database_id = "YOUR_DATABASE_ID" # Replace with actual ID after creation

# Environment variables
[vars]
ENVIRONMENT = "production"
API_VERSION = "v1"

[env.development.vars]
ENVIRONMENT = "development"

# CORS settings
[build]
command = "npm run type-check"